### PR TITLE
Users/james/docs 1

### PR DESCRIPTION
**Pull request by JamesOwers**
Written docs notebook 1 - have a play and see what you think.

We should discuss how to release evaluated notebooks for viewing. It's a pain to version control these to what I propose is:
* Version control un-evaluated notebooks in the repo, but
* Link to evaluated version of the notebooks on gist, like this: https://gist.github.com/JamesOwers/e24bc2f51d02dc2c7cf9c0ebddc50ee4

Re: the somewhat random changes to downloader tests - I'm not too fussed about testing these as will likely move to use https://salu133445.github.io/muspy/ instead of using our own downloaders. I've ceased the actual downloading tests to reduce the time overhead for pytest and thus the travis ci.

### CODE REVIEW

**Comment by apmcleod** [comment]
Is there a good way to comment line-by-line on ipynb files here? I'll just write some specific comments below. Overall, I really like this!

I made all of these changes. Feel free to edit/revert as you wish.

**Getting the Data section**
- Maybe "In which corpus csv file, and on what line" ... ?
- I would personally drop "package", and capitalize as "MIDI Degradation Toolkit", like here: https://github.com/nltk/nltk which is also how we wrote it in the paper.
- I added a progress bar to extract zip, since it was quite slow. Feel free to revert.

**The Data**
- "69 is A4, concert pitch" -> it is more common to say "60 is C4". (And remove the pitch part, MIDI doesn't necessarily specify a pitch in Hz).
- The plot is awesome! I made the x_label "time (ms)".

**The metadata**
- The names of the degradations *are* in 
- Maybe "gives the following information for each excerpt:"

I had no idea about that "?" command, very cool!

**Comment by apmcleod** [comment]
I agree it can be a pain to version control evaluated notebooks. It is important to have the pre-evaluated versions somewhere, since they are sometimes slow and some people might be on mobile, no python, etc.

I didn't know you could save pre-evaluated versions on gist. That's a good solution. Will they auto-update when we change something here?

On the other hand, these realistically won't be changing much, so it might be fine and simpler to just save a version evaluated once into the repo once they are all finalized. I would probably vote for this option.

**Review by apmcleod — APPROVED** [review]
LGTM with the changes I made (and outlined in my comment). Please check them. If you are fine with them, go ahead and merge.

We should discuss saving the notebooks in the repo or not. For now, saving only the un-evaluated versions is best, until we finalize them.

Really nicely done with this!

**Comment by apmcleod** [comment]
The build error was a connection reset by peer when downloading the ssl package. Technical issue, not our problem. It works fine.

**Comment by JamesOwers** [comment]
> I didn't know you could save pre-evaluated versions on gist. That's a good solution. Will they auto-update when we change something here?

No they wouldn't auto update, that would be a fancy solution that I'm sure someone somewhere knows how to do easily...but not me!


> On the other hand, these realistically won't be changing much, so it might be fine and simpler to just save a version evaluated once into the repo once they are all finalized. I would probably vote for this option.

Agreed - let's do this.

Changes are good, thanks! I'm now moving on son!

**Pull request merged**
